---
title: 'Milestone 2: Parking Data'
author: "Danah Dykstra, Jingyun Jia, Zhihao Lyu, Harshit Tummala"
date: "3/13/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggrepel)
library(scales)
library(patchwork)
```

```{r}
df = read_csv("maindf.csv")
head(df)
```

```{r}
# summary table to numerical values and their averages across the 5 largest counties
counties = c("Los Angeles", "Cook", "Harris", "Maricopa", "San Diego")
states = c("California", "Illinois", "Texas", "Arizona")

select_counties <- function(df){
  df %>% 
    select(County, State, AvgTimeToPark:AvgTotalGeohashes, PercentCar:PercentOther, POPESTIMATE2020:RNETMIG2020) %>% 
    group_by(County, State) %>%
    mutate_at(vars(AvgTimeToPark:AvgTotalGeohashes, PercentCar:PercentOther), mean)
}

all_county_sum <- df %>% 
  select_counties() %>% 
  mutate(State = ifelse(test = State %in% state.name, 
                        yes = state.abb[match(State, state.name)], 
                        no = str_replace_all(gsub(" ", "", State), "[:lower:]+", ""))) %>% 
  unique()
```


```{r, fig.height = 6}
some_county_sum <- all_county_sum %>% 
  arrange(-POPESTIMATE2020) %>% 
  head(15)

some_county_sum_small <- all_county_sum %>% 
  arrange(POPESTIMATE2020) %>%
  head(15)

p_big <- ggplot()+
  geom_bar(data=some_county_sum, aes(y = reorder(County, POPESTIMATE2020), x = AvgTimeToPark), stat = "identity")+
  scale_x_continuous(limits = c(0,10))+
  labs(x = "Average time to park",
       y = "County")

p_small <- ggplot()+
  geom_bar(data=some_county_sum_small, aes(y = reorder(County, POPESTIMATE2020), x = AvgTimeToPark), stat = "identity")+
  labs(x = "Average time to park",
       y = "County")

p_big/p_small+
  plot_layout(guides="collect")+
  plot_annotation(title = "Average Time to Park by County",
                   subtitle = "Top 15 and bottom 15 populous counties")

ggplot(all_county_sum)+
  geom_point(aes(x = AvgTimeToPark, y=POPESTIMATE2020, alpha = PercentSearching))+
  geom_text_repel(aes(x=AvgTimeToPark, y=POPESTIMATE2020, label=County))+
  labs(x = "Average Time to Park",
       y = "Population Estimate (by county 2020)",
       title = "Population vs. Average Time to Park",
       alpha = "Percent Searching",
       subtitle = "By County, Alpha by Percentage of Drivers Searching for Parking")+
  scale_y_continuous(label=comma)
```