---
title: "mileston2"
author: "Zhihao Lyu"
date: "3/13/2022"
output: html_document
---

```{r message=F, warning=F}
library(tidyverse)
library(ggplot2)
library(readr)
library(sf)
library(ggmap)
library(leaflet)
d = read_csv('Searching_for_parking_NA.csv')
```

```{r eval=F}
d2 = d %>% st_as_sf(coords = c("Longitude", "Latitude"), crs=st_crs(4326))
ggplot(d2) +
  geom_sf(aes(geometry = geometry))
```

```{r eval=F}
pal = colorNumeric("plasma", c(0, 12))
leaflet(d) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addCircleMarkers(
    ~Longitude, ~Latitude, 
    label = ~Geohash, radius=0.2,
    color = ~pal(AvgTimeToPark)) %>%
  addLegend("topright", pal = pal, values = ~AvgTimeToPark,
    title = "Avg Park Time",
    labFormat = labelFormat(suffix = "min"),
    opacity = 1
  )
```

```{r}
register_google(key = "AIzaSyBW7PU2Ne1CM33WMaPreTbAImzGB22Pc6s")
c(left = -125, bottom = 25.75, right = -67, top = 49) %>%
  get_stamenmap(zoom = 5, maptype = "toner-lite") %>%
  ggmap() + geom_point(data = d, aes(x=Longitude, y=Latitude))
```

